/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedDataImportRouteImport } from './routes/_authenticated/data-import'
import { Route as AuthenticatedCompetitionsRouteImport } from './routes/_authenticated/competitions'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/_authenticated/performance',
    path: '/performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/_authenticated/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/_authenticated/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDataImportRoute = AuthenticatedDataImportRouteImport.update({
  id: '/_authenticated/data-import',
  path: '/data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompetitionsRoute =
  AuthenticatedCompetitionsRouteImport.update({
    id: '/_authenticated/competitions',
    path: '/competitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/_authenticated/communications',
    path: '/communications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/_authenticated/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/competitions': typeof AuthenticatedCompetitionsRoute
  '/data-import': typeof AuthenticatedDataImportRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/competitions': typeof AuthenticatedCompetitionsRoute
  '/data-import': typeof AuthenticatedDataImportRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/competitions': typeof AuthenticatedCompetitionsRoute
  '/_authenticated/data-import': typeof AuthenticatedDataImportRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/changelog'
    | '/communications'
    | '/competitions'
    | '/data-import'
    | '/feedback'
    | '/knowledge'
    | '/performance'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/changelog'
    | '/communications'
    | '/competitions'
    | '/data-import'
    | '/feedback'
    | '/knowledge'
    | '/performance'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/admin'
    | '/_authenticated/changelog'
    | '/_authenticated/communications'
    | '/_authenticated/competitions'
    | '/_authenticated/data-import'
    | '/_authenticated/feedback'
    | '/_authenticated/knowledge'
    | '/_authenticated/performance'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCompetitionsRoute: typeof AuthenticatedCompetitionsRoute
  AuthenticatedDataImportRoute: typeof AuthenticatedDataImportRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/data-import': {
      id: '/_authenticated/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof AuthenticatedDataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competitions': {
      id: '/_authenticated/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof AuthenticatedCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCompetitionsRoute: AuthenticatedCompetitionsRoute,
  AuthenticatedDataImportRoute: AuthenticatedDataImportRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
